name: CI-deneme
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: pip install pytest
          pip install pandas
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: pytest test/
